/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"
#include "my_switch.h"




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "gpio.h"

int main(void) {
    GPIO_Init();

    uint8_t state = 0;
    uint8_t lastSwitch = 0;

    while (1) {
        uint8_t currentSwitch = Read_Switch();

        if (currentSwitch && !lastSwitch) {
            state++;
            if (state > 3) state = 1;

            // Reset LEDs
            LED_Off(12);
            LED_Off(15);

            // State machine
            switch (state) {
                case 1: LED_On(12); break;
                case 2: LED_On(15); break;
                case 3: /* Both OFF */ break;
            }
        }

        lastSwitch = currentSwitch;
    }
}




