/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"





#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



#include "gpio.h"

int main(void) {
    led_init();
    switch_init();

    int led_state = 0;
    int prev_press = 0;

    while (1) {
        int current_press = switch_pressed();


        if (current_press && !prev_press) {

            if (led_state) {
                led_off();
                led_state = 0;
            } else {
                led_on();
                led_state = 1;
            }
        }


        prev_press = current_press;
    }
}







